repos:
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      python_version: python3.6

-   repo: https://gitlab.com/pycqa/flake8
    rev: master
    hooks:
    -   id: flake8
        python_version: python3.6

-   repo: https://github.com/pre-commit/mirrors-isort
    rev: master  # Use the revision sha / tag you want to point at
    hooks:
    -   id: isort
        python_version: python3.6